name: Deploy React App
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: main # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
      - name: Deploy to GH Pages
        run: | 
        git config --global user.name "mreshtaiwi",
        git remote set-url origin git@github.com:mreshtaiwi/reactdeploment.get,
        npm install,
        npm run deploy
